### ISSUE TITLE
Provide system.svg for megadrive system

### ISSUE THREAD

**Issue by jesusignazio** [rxbrad/es-theme-gbz35#12]
In both configurations (genesis/megadrive) the system.svg file shows only art from sega genesis.

**Comment by rxbrad** [comment]
The megadrive folder's system.svg has been updated to the appropriate logo.

For US users, to view the Genesis logo again, see the note at the bottom of the page here: https://github.com/retropie/retropie-setup/wiki/Mega-Drive-Genesis
