### ISSUE TITLE
Image to video snap delay

### ISSUE THREAD

**Issue by trevor7oaks** [rxbrad/es-theme-gbz35#18]
Hi is there a way to remove the gap/delay between the game image and video snap, or remove the image so the video snaps play straight away?

**Comment by rxbrad** [comment]
Sorry about the ridiculous wait on getting back to you on this.  To change the delay, edit the gbz35.xml file.  

Find this line (it's line 110 at the moment): <delay>1</delay>  

The "1" is the number of seconds it waits to show the video.  Reduce the number to reduce the delay.

If you want to just skip straight to the video, you can also change line 112 from this:
<showSnapshotDelay>true</showSnapshotDelay>

...to this:
<showSnapshotDelay>false</showSnapshotDelay>
