### ISSUE TITLE
Add zx-spectrum

### ISSUE THREAD

**Issue by Senuxas** [rxbrad/es-theme-gbz35#20]

**Comment by mentazm** [comment]
I would also like this. I love the dark theme, it's my fave theme for the gpi case, but zx spectrum is missing.

**Comment by rxbrad** [comment]
This is (finally) done.  Thanks!

**Comment by mentazm** [comment]
Nice one brother!
Iain
    On Wednesday, 20 November 2019, 21:03:17 GMT, Brad <notifications@github.com> wrote:  
 
 
This is (finally) done. Thanks!
