### ISSUE TITLE
Game Gear Logo cropped on right side.

### ISSUE THREAD

**Issue by Sinistral2099** [rxbrad/es-theme-gbz35#22]
The Game Gear logo is cropped on the right side. Unsure if this is a problem with the image file or the theme.

**Comment by rxbrad** [comment]
Sorry about the late reply.  Looks like this happened after an EmulationStation update a couple versions ago.  There appear to be a few other logos that also get chopped off on the right edge (like Atari 800).  

I'll work on manually adding some margin to the affected systems' SVG files to prevent this.  Should hopefully be done sometime in the next month or two (possibly earlier even).

**Comment by rxbrad** [comment]
I went through all of the existing system logos and added margins until ES no longer clipped any of the edges.
