### ISSUE TITLE
Menu/start-button - Update the fonts

### ISSUE THREAD

**Issue by PushkaCom** [rxbrad/es-theme-gbz35#26]
**EDIT** - I thought that the issue was solved, but I think that it may still not be possible to adjust the menu font, jsut that every external reference to it is being closed and forwarded to the thread? 
**OR** - possibly my Retrostone2 is uring Retropie-4.3 and doesn't have this help-menu-style-font-update, so I need to wait for the system update?
https://github.com/RetroPie/EmulationStation/pull/146

Hi - I love the dark version of this theme - I'm using it/ customising it a bit on the Retrostone-2 (portable gameboy linux pc)

I switched out the font, but the menu is not themed, do you know how to adjust this font too?

There was an issue raised that this font was not editable - but it was marked as fixed, I just don't know how to update it - do you know how to change that font, and would you be able to add it into the themes? 

Links to bug reports and fix-status:

start-menu font is not changing 
Issue:
https://github.com/RetroPie/EmulationStation/issues/144
Fixed with this: (?)
https://github.com/RetroPie/EmulationStation/pull/146 

Screenshot - Help-menu:

![image](https://user-images.githubusercontent.com/985223/73810566-03a28e80-482b-11ea-9e18-90834fa22436.png)

**Comment by rxbrad** [comment]
The "Help Menu" that can be modified by themes is actually just that row at the bottom of the screen listing the buttons and their functions. ( Described at the very end of this piece of documentation: [https://github.com/RetroPie/EmulationStation/blob/master/THEMES.md](https://github.com/RetroPie/EmulationStation/blob/master/THEMES.md) )

The Main Menu in your screenshot is, unfortunately, not yet themeable.  It sounds like there were some font inconsistencies (which I vaguely recall) between different menu items that were eventually resolved.
