### ISSUE TITLE
Crashing ES

### ISSUE THREAD

**Issue by jondeckert** [rxbrad/es-theme-gbz35#28]
When I select this theme, it’s crashing Emulation Station to the command prompt.

**Comment by rxbrad** [comment]
Hmm...  It's working okay for me on these three different EmulationStation setups:

- Raspberry Pi Zero RetroPie (kind of hard to read on my Gameboy Zero, but looks like EmulationStation v2.11.4)
- EmulationStation v2.9.0 on Windows 10
- EmulationStation v2.7.4 in Windows 10

What platform are you running EmulationStation on? Retropie/Raspberry Pi? PC? Other? Also, which version of EmulationStation are you running?

I hate to throw it back in your court, but I wonder if something is misconfigured on your end?  Also, are you maybe trying to view the theme in Grid View (it's not supported in this theme.. though I wouldn't think it'd crash ES outright).

Did it crash before I added openbor?

**Comment by jondeckert** [comment]
No problem, throwing it back my way. I'd rather help out. I am using RetroPie through a RetroFlag GpiCase with a Raspberry Pi Zero W. Not certain which version of Emulation Station but I am using the Gpi Case User's Group Image which is based on RetroPie 4.5.1. Where can I locate the version number? I don't recall it crashing before you added OpenBor. The crash happens when I attempt to switch to the theme via UI Settings and only via that theme. Any other themes I use, do not present a crash. I have uninstalled and reinstalled the theme and it persists.  I am viewing the theme on auto, haven't tried grid for any themes.

**Comment by rxbrad** [comment]
I managed to get it to crash by attempting to add OpenBOR via the "Create New Custom Collection From Theme" option on my Pi Zero handheld.  (I had to do it by that method, since OpenBOR gets dumped into the "Ports" menu by default when you install it)

So, maybe the version of ES on the Pi (Start button menu shows it to you in _tiny_ text at the bottom) doesn't like something about the SVG file being used for the logo.

I'll do some more investigation and report back (might be tomorrow or so before I can get it fixed).  Thanks for the heads up.

**Comment by jondeckert** [comment]
I appreciate you looking into it. Looks like I am running ES Version 2.84 from what I can tell from the small text.

**Comment by rxbrad** [comment]
I vectorized a new OpenBOR logo from scratch.  Using the new logo, it no longer crashes EmulationStation when I view OpenBOR in RetroPie on my Pi Zero handheld.

**Comment by jondeckert** [comment]
Confirmed! Works and looks great! Thank you! No rush but would be great if this was also added to the dark version.

**Comment by rxbrad** [comment]
@jondeckert I actually updated the dark theme at the same time, so it should hopefully be good to go.
