### ISSUE TITLE
Dos theme is too bright red

### ISSUE THREAD

**Issue by hex007** [rxbrad/es-theme-gbz35#5]
The Dark dos theme could have a simpler colour than bright red

**Comment by rxbrad** [comment]
Sorry..  working as intended at this point.  Basic color scheme is orange/red/turquoise/green/blue/purple, and I just try to randomize it across the different system.

Here's the graphic template I use in GIMP to create the ones that weren't in SimpleBigArt.  I use a color layer + an all-black image at 15% opacity.  If you'd like to make a different color, you can totally do so.  I usually use the controller.svg files from carbon as a starting point for the system overlay on the background.

[GBZ35-Backgrounds.zip](https://github.com/rxbrad/es-theme-gbz35/files/1155925/GBZ35-Backgrounds.zip)
